config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'yurikohomes#index'
  resources :yurikohomes, only: :index
  resources :bustups
  resources :halfbodies
  resources :fullbodies
  resources :chibis
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bustup.rb
class Bustup < ApplicationRecord
  has_one_attached :image
  validates :image, presence: true
  validates :title, presence: true

end

app/models/chibi.rb
class Chibi < ApplicationRecord
  has_one_attached :image
  validates :image, presence: true
  validates :title, presence: true
end

app/models/fullbody.rb
class Fullbody < ApplicationRecord
  has_one_attached :image
  validates :image, presence: true
  validates :title, presence: true

end

app/models/halfbody.rb
class Halfbody < ApplicationRecord
  has_one_attached :image
  validates :image, presence: true
  validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :password,            presence: true, format:{with:/351701/}
  validates :email,               presence: true, format:{with:/chanebu@gmail.com/}

end

app/models/yurikohome.rb
class Yurikohome < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bustups_controller.rb
class BustupsController < ApplicationController

  before_action :set_item, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @bustups = Bustup.all
  end

  def new
    @bustup = Bustup.new
  end

  def create
    @bustup = Bustup.new(bustup_params)
    if @bustup.save
      redirect_to bustups_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @bustup.update(bustup_params)
      redirect_to bustup_path(@bustup.id)
    else
      render :edit
    end
  end

  def destroy
    @bustup.destroy
    redirect_to bustups_path
  end

  private
  def bustup_params
    params.require(:bustup).permit(:title,:image)
  end

  def set_item
    @bustup = Bustup.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/chibis_controller.rb
class ChibisController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
   @chibis = Chibi.all
  end
 
 def new
   @chibi= Chibi.new
 end
 
 def create
   @chibi = Chibi.new(chibi_params)
   if @chibi.save
     redirect_to chibis_path
   else
       render :new
   end
 end
 
 def show
 end
 
 def edit
 end
 
 def update
   if @chibi.update(chibi_params)
     redirect_to chibi_path(@chibi.id)
   else
     render :edit
   end
 end
 
 def destroy
   @chibi.destroy
   redirect_to chibis_path
 end
 
 private
   def chibi_params
     params.require(:chibi).permit(:title,:image)
   end
 
   def set_item
     @chibi = Chibi.find(params[:id])
   end

   def move_to_index
    redirect_to action: :index unless user_signed_in?
  end


end

app/controllers/fullbodies_controller.rb
class FullbodiesController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

   def index
    @fullbodies = Fullbody.all
   end
  
  def new
    @fullbody = Fullbody.new
  end
  
  def create
    @fullbody = Fullbody.new(fullbody_params)
    if @fullbody.save
      redirect_to fullbodies_path
    else
        render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @fullbody.update(fullbody_params)
      redirect_to halfbody_path(@fullbody.id)
    else
      render :edit
    end
  end
  
  def destroy
    @fullbody.destroy
    redirect_to fullbodies_path
  end
  
  private
    def fullbody_params
      params.require(:fullbody).permit(:title,:image)
    end
  
    def set_item
      @fullbody = Fullbody.find(params[:id])
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
  
end

app/controllers/halfbodies_controller.rb
class HalfbodiesController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @halfbodies = Halfbody.all
  end

  def new
    @halfbody = Halfbody.new
  end

  def create
    @halfbody = Halfbody.new(halfbody_params)
    if @halfbody.save
      redirect_to halfbodies_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @halfbody.update(halfbody_params)
      redirect_to halfbody_path(@halfbody.id)
    else
      render :edit
    end
  end

  def destroy
    @halfbody.destroy
    redirect_to halfbodies_path
  end

  private
  def halfbody_params
    params.require(:halfbody).permit(:title,:image)
  end

  def set_item
    @halfbody = Halfbody.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/yurikohomes_controller.rb
class YurikohomesController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bustups_helper.rb
module BustupsHelper
end

app/helpers/chibis_helper.rb
module ChibisHelper
end

app/helpers/fullbodies_helper.rb
module FullbodiesHelper
end

app/helpers/halfbodys_helper.rb
module HalfbodysHelper
end

app/helpers/yurikohomes_helper.rb
module YurikohomesHelper
end

app/views/bustups/edit.html.erb
<div class='n-e-field'>
  <div class='n-e-title'>
    編集
  </div>
  <div class="contents ">
    <div class="container">
      <%= form_with(model: @bustup, local: true) do |form| %>
      <div class='item'>
        <%= form.file_field :image, id:"bustup_image" %>
      </div>
      <div class='item'>
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>
      <div class='item'>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <%= link_to '戻る', bustups_path, method: :get %>
    </div>
  </div>
</div>

app/views/bustups/index.html.erb
<div class='bu-index'>
  <div class='new-up-road'>
    <div class='new-up'>
      <h3>新規投稿</h3>
    </div>
    <div class='up-road'>
      <%= link_to image_tag('icons8-アップロード.gif'), new_bustup_path, method: :get %>
    </div>
  </div>
  <div class='index-images'>
    <% @bustups.each do | bustup |%>
      <%= link_to bustup_path(bustup.id), method: :get do %>
      <div>
       <%= image_tag(bustup.image, class: 'index-image')%>
      </div>
      <div class='index-title'>
       <%=bustup.title%>
      </div>
      <%end%>
    <%end%>
    <% if @bustups[0]==nil%>
      <%= image_tag('development.jpg', class: 'index-image')%>
    <%end%>

  </div>
</div>
<div class='icon-rinks'>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/qBWvwdEFQ7kE/アップロード">アップロード</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
</div>

app/views/bustups/new.html.erb
<div class='n-e-field'>
  <div class='n-e-title'>
    新規投稿
  </div>
  <div class="contents ">
    <div class="container">
      <%= form_with(model: @bustup,id:"all_image", local: true) do |form| %>
      <div class='item'>
        <div id="previews"></div>
        <%= form.file_field :image, id:"all_image" %>
      </div>
      <div class='item'>
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>
      <div class='item'>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <%= link_to '戻る', bustups_path, method: :get %>
    </div>
  </div>
</div>

app/views/bustups/show.html.erb
<div class='show-field' >
  <div class='show-title'> 
    <%=@bustup.title%>
  </div>
  <div class='show-items'>
    <%= image_tag(@bustup.image, class: 'show-image')%>
  </div>
  <div class='btn'>
  <% if user_signed_in? %>
    <div class='edit'>
      <%= link_to image_tag('icons8-編集.gif'), edit_bustup_path(@bustup.id), method: :get %>
    </div>
    <div class='destory'>
      <%= link_to image_tag('icons8-削除.gif'), bustup_path(@bustup.id), method: :delete %>
    </div>
  <% end %>
    <div class='back'>
      <%= link_to image_tag('icons8-uターン.gif'), bustups_path, method: :get %>
    </div>
  </div>
</div>
<div class='icon-rinks'>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/1RHO78Nco12i/編集">編集</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/aJXCfqpXgZUC/削除">削除</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/OSSYyxbtK8gQ/uターン">Uターン</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
</div>

app/views/chibis/edit.html.erb
<div class='n-e-field'>
  <div class='n-e-title'>
    編集
  </div>
  <div class="contents ">
    <div class="container">
      <%= form_with(model: @chibi, local: true) do |form| %>
      <div class='item'>
        <%= form.file_field :image, id:"chibi_image" %>
      </div>
      <div class='item'>
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>
      <div class='item'>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <%= link_to '戻る', chibis_path, method: :get %>
    </div>
  </div>
</div>

app/views/chibis/index.html.erb
<div class='bu-index'>
  <div class='new-up-road'>
    <div class='new-up'>
      <h3>新規投稿</h3>
    </div>
    <div class='up-road'>
      <%= link_to image_tag('icons8-アップロード.gif'), new_chibi_path, method: :get %>
    </div>
  </div>
  <div class='index-images'>
    <% @chibis.each do | chibi |%>
      <%= link_to chibi_path(chibi.id), method: :get do %>
      <div>
       <%= image_tag(chibi.image, class: 'index-image')%>
      </div>
      <div class='index-title'>
       <%=chibi.title%>
      </div>
      <%end%>
    <%end%>
    <% if @chibis[0]==nil%>
      <%= image_tag('development.jpg', class: 'index-image')%>
    <%end%>
  </div>
</div>
<div class='icon-rinks'>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/qBWvwdEFQ7kE/アップロード">アップロード</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
</div>

app/views/chibis/new.html.erb
<div class='n-e-field'>
  <div class='n-e-title'>
    新規投稿
  </div>
  <div class="contents ">
    <div class="container">
      <%= form_with(model: @chibi, local: true) do |form| %>
      <div class='item'>
      <div id="previews"></div>
        <%= form.file_field :image, id:"all_image" %>
      </div>
      <div class='item'>
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>
      <div class='item'>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <%= link_to '戻る', chibis_path, method: :get %>
    </div>
  </div>
</div>

app/views/chibis/show.html.erb
<div class='show-field' >
  <div class='show-title'> 
    <%=@chibi.title%>
  </div>
  <div class='show-items'>
    <%= image_tag(@chibi.image, class: 'show-image')%>
  </div>
  <div class='btn'>
  <% if user_signed_in? %>
    <div class='edit'>
      <%= link_to image_tag('icons8-編集.gif'), edit_chibi_path(@chibi.id), method: :get %>
    </div>
    <div class='destory'>
      <%= link_to image_tag('icons8-削除.gif'), chibi_path(@chibi.id), method: :delete %>
    </div>
    <% end %>
  <div class='back'>
      <%= link_to image_tag('icons8-uターン.gif'), chibi_path, method: :get %>
    </div>
  </div>
</div>
<div class='icon-rinks'>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/1RHO78Nco12i/編集">編集</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/aJXCfqpXgZUC/削除">削除</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/OSSYyxbtK8gQ/uターン">Uターン</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
</div>

app/views/fullbodies/edit.html.erb
<div class='n-e-field'>
  <div class='n-e-title'>
    編集
  </div>
  <div class="contents ">
    <div class="container">
      <%= form_with(model: @fullbody, local: true) do |form| %>
      <div class='item'>
        <%= form.file_field :image, id:"fullbody_image" %>
      </div>
      <div class='item'>
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>
      <div class='item'>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <%= link_to '戻る', fullbodies_path, method: :get %>
    </div>
  </div>
</div>

app/views/fullbodies/index.html.erb
<div class='bu-index'>
  <div class='new-up-road'>
    <div class='new-up'>
      <h3>新規投稿</h3>
    </div>
    <div class='up-road'>
      <%= link_to image_tag('icons8-アップロード.gif'), new_fullbody_path, method: :get %>
    </div>
  </div>
  <div class='index-images'>
    <% @fullbodies.each do | fullbody |%>
      <%= link_to fullbody_path(fullbody.id), method: :get do %>
      <div>
       <%= image_tag(fullbody.image, class: 'index-image')%>
      </div>
      <div class='index-title'>
       <%=fullbody.title%>
      </div>
      <%end%>
    <%end%>
    <% if @fullbodies[0]==nil%>
      <%= image_tag('development.jpg', class: 'index-image')%>
    <%end%>
  </div>
</div>
<div class='icon-rinks'>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/qBWvwdEFQ7kE/アップロード">アップロード</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
</div>

app/views/fullbodies/new.html.erb
<div class='n-e-field'>
  <div class='n-e-title'>
    新規投稿
  </div>
  <div class="contents ">
    <div class="container">
      <%= form_with(model: @fullbody, local: true) do |form| %>
      <div class='item'>
      <div id="previews"></div>
        <%= form.file_field :image, id:"all_image" %>
      </div>
      <div class='item'>
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>
      <div class='item'>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <%= link_to '戻る', fullbodies_path, method: :get %>
    </div>
  </div>
</div>

app/views/fullbodies/show.html.erb
<div class='show-field' >
  <div class='show-title'> 
    <%=@fullbody.title%>
  </div>
  <div class='show-items'>
    <%= image_tag(@fullbody.image, class: 'show-image')%>
  </div>
  <div class='btn'>
  <% if user_signed_in? %>
    <div class='edit'>
      <%= link_to image_tag('icons8-編集.gif'), edit_fullbody_path(@fullbody.id), method: :get %>
    </div>
    <div class='destory'>
      <%= link_to image_tag('icons8-削除.gif'), fullbody_path(@fullbody.id), method: :delete %>
    </div>
  <% end %>
    <div class='back'>
      <%= link_to image_tag('icons8-uターン.gif'), fullbody_path, method: :get %>
    </div>
  </div>
</div>
<div class='icon-rinks'>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/1RHO78Nco12i/編集">編集</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/aJXCfqpXgZUC/削除">削除</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/OSSYyxbtK8gQ/uターン">Uターン</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
</div>

app/views/halfbodies/edit.html.erb
<div class='n-e-field'>
  <div class='n-e-title'>
    編集
  </div>
  <div class="contents ">
    <div class="container">
      <%= form_with(model: @halfbody, local: true) do |form| %>
      <div class='item'>
        <%= form.file_field :image, id:"halfbody_image" %>
      </div>
      <div class='item'>
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>
      <div class='item'>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <%= link_to '戻る', halfbodies_path, method: :get %>
    </div>
  </div>
</div>

app/views/halfbodies/index.html.erb
<div class='bu-index'>
  <div class='new-up-road'>
    <div class='new-up'>
      <h3>新規投稿</h3>
    </div>
    <div class='up-road'>
      <%= link_to image_tag('icons8-アップロード.gif'), new_halfbody_path, method: :get %>
    </div>
  </div>
  <div class='index-images'>
    <% @halfbodies.each do | halfbody |%>
      <%= link_to halfbody_path(halfbody.id), method: :get do %>
      <div>
       <%= image_tag(halfbody.image, class: 'index-image')%>
      </div>
      <div class='index-title'>
       <%=halfbody.title%>
      </div>
      <%end%>
    <%end%>
    <% if @halfbodies[0]==nil%>
      <%= image_tag('development.jpg', class: 'index-image')%>
    <%end%>
  </div>
</div>
<div class='icon-rinks'>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/qBWvwdEFQ7kE/アップロード">アップロード</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
</div>

app/views/halfbodies/new.html.erb
<div class='n-e-field'>
  <div class='n-e-title'>
    新規投稿
  </div>
  <div class="contents ">
    <div class="container">
      <%= form_with(model: @halfbody, local: true) do |form| %>
      <div class='item'>
      <div id="previews"></div>
        <%= form.file_field :image, id:"all_image" %>
      </div>
      <div class='item'>
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>
      <div class='item'>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <%= link_to '戻る', halfbodies_path, method: :get %>
    </div>
  </div>
</div>

app/views/halfbodies/show.html.erb
<div class='show-field' >
  <div class='show-title'> 
    <%=@halfbody.title%>
  </div>
  <div class='show-items'>
    <%= image_tag(@halfbody.image, class: 'show-image')%>
  </div>
  <div class='btn'>
  <% if user_signed_in? %>
    <div class='edit'>
      <%= link_to image_tag('icons8-編集.gif'), edit_halfbody_path(@halfbody.id), method: :get %>
    </div>
    <div class='destory'>
      <%= link_to image_tag('icons8-削除.gif'), halfbody_path(@halfbody.id), method: :delete %>
    </div>
  <% end %>
    <div class='back'>
      <%= link_to image_tag('icons8-uターン.gif'), halfbody_path, method: :get %>
    </div>
  </div>
</div>
<div class='icon-rinks'>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/1RHO78Nco12i/編集">編集</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/aJXCfqpXgZUC/削除">削除</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
  <div class='icon-rink'>
    <a target="_blank" href="https://icons8.com/icon/OSSYyxbtK8gQ/uターン">Uターン</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <div>
      <title>Uyayuriko</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="head">
      <div class="header">
        <%= link_to image_tag('ウヤユリコヘッダー.jpg', class:'headimg'), '/'%>
        <div class='signup'>
          <ul class='lists-right'>
            <% if user_signed_in? %>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
            <% else %>
            <div>
              <%= link_to 'ログイン', new_user_session_path, class: "login" %><br>
            </div>
            <div>
              <%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>
            </div>
            <% end %>
          </ul>

        <div class="user_nav grid-6">
         
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
     <div class = footer-field>
      <div class = rink>
       <%= link_to image_tag('ツイッターアイコン.jpeg', class:"icon"), "https://twitter.com/YURiKO830" %>
       <%= link_to image_tag('Instagram_Glyph_Gradient_RGB.png', class:"icon"), "https://www.instagram.com/yuriko__83/" %>
       <%= link_to image_tag('YouTube_23392.png', class:"icon"), "https://www.youtube.com/channel/UC0nWgr7qxT0RtS69Fidb7Kw/featured" %>
       <%= link_to image_tag('tiktok_logo_icon_188431.png', class:"icon"), "https://www.tiktok.com/@yurikooooo830" %>
      </div>
     </div>
    </footer>
  </body>
</html>

app/views/yurikohomes/index.html.erb
<div class = "main-field">
 <div class = main-images>
  <div class="main-images1">
    <%= link_to image_tag('halfbodyテスト.png', class:"category"), halfbodies_path %>
    <div class = "category-name">
     ハーフボディー
    </div>
  </div>
  <div class="main-images1">
    <%= link_to image_tag('バストアップテスト.jpg', class:"category"), bustups_path %>
    <div class = "category-name">
     バストアップ
    </div>
  </div>
 </div>
 <div class = main-images>
  <div class="main-images1">
    <%= link_to image_tag('fullbodyテスト.png', class:"category"), fullbodies_path %>
    <div class = "category-name">
     フルボディー
    </div>
  </div>
  <div class="main-images1">
    <%= link_to image_tag('chibiテスト.png', class:"category"), chibis_path %>
    <div class = "category-name">
     ちびすたいる
    </div>
  </div>
 </div>
</div>